### ISSUE TITLE
I believe "NegativeSrcAlpha" and similar to be misnomers.

### ISSUE THREAD

**Issue by xorgy** [phaazon/luminance-gl-rs#1]
ONE_MINUS_SRC_ALPHA is the complement of the source alpha in one, not a negative of the source alpha. I do not think `NegativeSrcAlpha` is a correct name for this. There are other similar name changes which also do not make sense.

See https://github.com/phaazon/luminance-gl-rs/blob/master/src/gl33/render.rs#L77 for an example.

**Comment by phaazon** [comment]
I guess you’re right. I wrote that in a hurry at a demoparty, I shall change it :).
